In [44]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
file_to_load = "purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)

In [2]:
purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [3]:
unique_users=purchase_data['SN'].unique()

In [4]:
Unique_user_count=len(unique_users)
print(Unique_user_count)

576

In [5]:
print("Total Players: ", str(len(unique_users)))

Total Players:  576

In [6]:

#Purchasing Analysis (Total)
#Run basic calculations to obtain number of unique items, average price, number of purchases,
#total revenue etc.
#Create a summary data frame to hold the results
#Optional: give the displayed data cleaner formatting
#Display the summary data frame

In [7]:
unique_items=purchase_data['Item ID'].unique()
total_unique_items=str(len(unique_items))
print("Unique Items: ", total_unique_items)

Unique Items:  183

In [8]:
purchase_data.describe()

       Purchase ID         Age     Item ID       Price
count   780.000000  780.000000  780.000000  780.000000
mean    389.500000   22.714103   92.114103    3.050987
std     225.310896    6.659444   52.775943    1.169549
min       0.000000    7.000000    0.000000    1.000000
25%     194.750000   20.000000   48.000000    1.980000
50%     389.500000   22.000000   93.000000    3.150000
75%     584.250000   25.000000  139.000000    4.080000
max     779.000000   45.000000  183.000000    4.990000

In [9]:
item_price_list=purchase_data.groupby('Item ID').mean()
item_price_list = item_price_list.drop('Purchase ID', 1)
item_price_list = item_price_list.drop('Age', 1)

In [10]:
print(item_price_list)

         Price
Item ID
0         1.28
1         3.26
2         2.48
3         2.49
4         1.70
5         4.08
6         3.70
7         1.33
8         3.93
9         2.73
10        1.79
11        3.65
12        1.02
13        1.41
14        2.61
15        2.96
16        3.55
17        1.70
18        4.65
19        1.02
20        3.27
21        1.10
22        2.18
23        1.99
24        3.81
25        4.35
26        1.12
27        3.30
28        1.06
29        1.98
...        ...
154       4.40
155       1.01
156       1.77
157       4.80
158       2.45
159       3.08
160       4.40
161       1.76
162       2.67
163       3.45
164       1.63
165       4.86
166       3.07
167       3.61
168       1.48
169       2.18
170       3.97
171       1.79
172       3.14
173       4.93
174       3.47
175       4.48
176       2.84
177       2.08
178       4.23
179       4.48
180       3.36
181       1.66
182       4.03
183       1.09

[183 rows x 1 columns]

In [11]:
average_price=item_price_list.mean()[0]
average_price

3.0433879781420767

In [12]:
number_of_purchases=len(purchase_data)
print("Total Purchases: ", number_of_purchases)

Total Purchases:  780

In [13]:
revenue_column=purchase_data.drop('Age', 1)
revenue_column=revenue_column.drop('Purchase ID',1)
revenue_column=revenue_column.drop('SN',1)
revenue_column=revenue_column.drop('Gender',1)
revenue_column=revenue_column.drop('Item ID',1)
revenue_column=revenue_column.drop('Item Name',1)

In [14]:
revenue_column

     Price
0     3.53
1     1.56
2     4.88
3     3.27
4     1.44
5     3.61
6     2.18
7     2.67
8     1.10
9     3.58
10    4.74
11    2.67
12    4.18
13    1.70
14    4.86
15    2.89
16    2.52
17    1.76
18    4.90
19    4.64
20    4.60
21    1.48
22    3.81
23    3.40
24    3.19
25    4.23
26    1.61
27    3.09
28    4.32
29    3.16
..     ...
750   3.61
751   3.36
752   2.60
753   4.23
754   4.05
755   3.15
756   2.05
757   4.60
758   4.03
759   3.77
760   2.38
761   1.70
762   1.44
763   1.75
764   4.07
765   2.07
766   4.14
767   4.88
768   4.88
769   4.58
770   1.02
771   4.35
772   3.58
773   1.02
774   4.19
775   3.54
776   1.63
777   3.46
778   4.19
779   4.60

[780 rows x 1 columns]

In [15]:
total_revenue=revenue_column.sum()[0]
total_revenue

2379.77

In [16]:
print("Unique Items: ", str(len(unique_items)))
print("Total Purchases: ", number_of_purchases)
print("Average Price: ",average_price)
print("Total Revenue: ",total_revenue)

Unique Items:  183
Total Purchases:  780
Average Price:  3.0433879781420767
Total Revenue:  2379.77

In [17]:
purch_dict = {
    'Number of Unique Items':total_unique_items,
    'Average Price':average_price,
    'Number of Purchases':number_of_purchases,
    'Total Revenue':total_revenue}

Purchasing_Analaysis_df = pd.DataFrame(purch_dict, index=[0])
Purchasing_Analaysis_df

  Number of Unique Items  Average Price  Number of Purchases  Total Revenue
0                    183       3.043388                  780        2379.77

In [18]:
gender_unique=purchase_data.groupby('SN').first()
gender_unique

,Purchase ID,Age,Gender,Item ID,Item Name,Price
SN,,,,,,
Adairialis76,467,16,Male,123,Twilight's Carver,2.28
Adastirin33,142,35,Female,175,Woeful Adamantite Claymore,4.48
Aeda94,388,17,Male,128,"Blazeguard, Reach of Eternity",4.91
Aela59,28,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32
Aelaria33,630,23,Male,171,Scalpel,1.79
Aelastirin39,218,23,Male,76,Haunted Bronzed Bludgeon,3.15
Aelidru27,705,22,Male,183,Dragon's Greatsword,1.09
Aelin32,52,20,Male,60,Wolf,3.54
Aelly27,43,24,Male,116,Renewed Skeletal Katana,4.18
Aellynun67,286,25,Male,153,Mercenary Sabre,3.74
Aellyria80,746,23,Male,159,"Oathbreaker, Spellblade of Trials",3.08
Aelollo59,203,33,Male,3,Phantomlight,2.49
Aenarap34,183,21,Male,15,Soul Infused Crystal,2.96
Aeral43,263,24,Male,78,"Glimmer, Ender of the Moon",4.40
Aeral68,674,43,Male,77,"Piety, Guardian of Riddles",4.00
Aeral97,167,23,Male,157,"Spada, Etcher of Hatred",4.80
Aeralria27,32,10,Male,133,Faith's Scimitar,4.09
Aeralstical35,583,20,Male,49,"The Oculus, Token of Lost Worlds",2.96
Aeri84,303,24,Male,71,Demise,1.61
Aerillorin70,381,16,Male,83,Lifebender,3.33
Aerithllora36,274,29,Female,82,Nirvana,4.90
Aerithnucal56,324,15,Male,154,Feral Katana,4.40
Aerithnuphos61,517,39,Male,128,"Blazeguard, Reach of Eternity",4.91
Aerithriaphos45,40,20,Male,143,Frenzied Scimitar,1.56
Aerithriaphos46,236,16,Male,107,"Splitter, Foe Of Subtlety",2.18
Aesri53,541,31,Male,161,Devine,1.76
Aesty53,124,21,Male,150,Deathraze,2.85
Aestysu37,309,25,Male,170,Shadowsteel,3.97
Aesur96,468,23,Male,30,Stormcaller,2.21
Aesurstilis64,405,25,Male,70,Hope's End,1.03
...,...,...,...,...,...,...
Undosia27,229,17,Male,72,Winter's Bite,3.77
Undosian34,90,21,Male,60,Wolf,3.54
Undotesta33,704,18,Male,95,Singed Onyx Warscythe,4.74
Wailin72,283,21,Female,9,"Thorn, Conqueror of the Corrupted",2.73
Yadacal26,337,15,Male,17,"Lazarus, Terror of the Earth",1.70
Yadaisuir65,625,20,Male,133,Faith's Scimitar,4.09
Yadam35,553,28,Male,2,Verdict,2.48
Yadanu52,60,34,Male,44,Bonecarvin Battle Axe,2.38
Yadaphos40,62,30,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
Yalae81,5,22,Male,81,Dreamkiss,3.61
Yalaeria91,681,33,Male,28,"Flux, Destroyer of Due Diligence",1.06
Yaliru88,59,19,Male,105,Hailstorm Shadowsteel Scythe,3.03
Yalo85,383,34,Male,11,Brimstone,3.65
Yalostiphos68,518,29,Male,160,Azurewrath,4.40
Yana46,280,20,Female,16,Restored Bauble,3.55
Yarithllodeu72,364,22,Male,88,"Emberling, Defender of Delusions",3.75
Yarithrgue83,279,20,Male,163,Thunderfury Scimitar,3.45
Yarithrin84,698,30,Female,58,"Freak's Bite, Favor of Holy Might",4.14
Yarithsurgue62,231,26,Male,139,"Mercy, Katana of Dismay",4.94
Yarolwen77,696,30,Male,87,"Deluge, Edge of the West",4.43
Yasrisu92,46,27,Male,102,Avenger,3.44
Yastyriaphos75,340,22,Male,41,Orbit,4.75
Yasur35,257,26,Male,175,Woeful Adamantite Claymore,4.48
Yasur85,514,21,Male,21,Souleater,1.10
Yathecal72,777,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46
Yathecal82,125,20,Female,62,Piece Maker,1.87
Yathedeu43,93,22,Male,88,"Emberling, Defender of Delusions",3.75
Yoishirrala98,572,17,Female,145,Fiery Glass Crusader,4.58
Zhisrisu83,54,10,Male,25,Hero Cane,4.35
Zontibe81,17,21,Male,161,Devine,1.76

In [19]:
gender_counts=gender_unique.groupby(['Gender']).size().reset_index(name='counts')

In [20]:
gender_counts

                  Gender  counts
0                 Female      81
1                   Male     484
2  Other / Non-Disclosed      11

In [21]:
gender_counts = gender_counts.rename(columns={'counts': 'Total Count'})

In [22]:
gender_counts

                  Gender  Total Count
0                 Female           81
1                   Male          484
2  Other / Non-Disclosed           11

In [23]:
gender_counts['Percentage of Players'] = gender_counts['Total Count'] / Unique_user_count

In [24]:
gender_counts=gender_counts.set_index('Gender')
gender_counts

                       Total Count  Percentage of Players
Gender
Female                          81               0.140625
Male                           484               0.840278
Other / Non-Disclosed           11               0.019097

In [25]:
#Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender

In [26]:
purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

In [27]:
purch_count_gender=purchase_data.groupby('Gender').count()

In [32]:
purch_count_gender=purch_count_gender.drop(columns=['SN', 'Age','Item ID','Item Name','Price'])

In [62]:
purch_count_gender
purch_count_gender = purch_count_gender.rename(columns={'Purchase ID': 'Purchase Count'})
purch_count_gender

                       Purchase Count
Gender
Female                            113
Male                              652
Other / Non-Disclosed              15

In [38]:
purch_average_gender=purchase_data.groupby('Gender').mean()

In [40]:
purch_average_gender=purch_average_gender.drop(columns=['Age','Item ID','Purchase ID'])

In [41]:
purch_average_gender

                          Price
Gender
Female                 3.203009
Male                   3.017853
Other / Non-Disclosed  3.346000

In [64]:
purch_average_gender = purch_average_gender.rename(columns={'Price': 'Average Purchase Price'})

In [45]:
purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44
5,5,Yalae81,22,Male,81,Dreamkiss,3.61
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67
8,8,Undjask33,22,Male,21,Souleater,1.10
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89
16,16,Lisirra25,20,Male,40,Second Chance,2.52
17,17,Zontibe81,21,Male,161,Devine,1.76
18,18,Reunasu60,22,Female,82,Nirvana,4.90
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81
23,23,Eyrian71,40,Male,151,Severance,3.40
24,24,Siala43,30,Male,141,Persuasion,3.19
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
26,26,Lirtossa84,11,Male,71,Demise,1.61
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16
...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15
756,756,Ilast79,20,Male,73,Ritual Mace,2.05
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60
758,758,Iral74,21,Male,182,Toothpick,4.03
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70
762,762,Asur53,26,Male,110,Suspension,1.44
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07
765,765,Irith83,18,Male,130,Alpha,2.07
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14
767,767,Ilmol66,8,Female,92,Final Critic,4.88
768,768,Assassasta79,38,Male,92,Final Critic,4.88
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58
770,770,Lirtosia63,34,Male,12,Dawne,1.02
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02
774,774,Jiskjask80,11,Male,101,Final Critic,4.19
775,775,Aethedru70,21,Female,60,Wolf,3.54
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46
778,778,Sisur91,7,Male,101,Final Critic,4.19
779,779,Ennrian78,24,Male,50,Dawn,4.60

In [51]:
purch_amnt_gender_and_Indiv=purchase_data.groupby(['Gender', 'SN']).sum()

In [52]:
purch_amnt_gender_and_Indiv

                                      Purchase ID  Age  Item ID  Price
Gender                SN
Female                Adastirin33             142   35      175   4.48
                      Aerithllora36           852   58      235   8.64
                      Aethedru70              775   21       60   3.54
                      Aidain51                516   39       35   3.45
                      Aiduesu86               429   22      179   4.48
                      Aillyrin83              155   10       98   2.89
                      Aisurdru79             1058   58      258   3.51
                      Assilsan72              666   20       82   4.90
                      Assosia88                41   20        7   1.33
                      Baelollodeu94           747   40      144   9.03
                      Chadistaya75             92   21       39   3.94
                      Chamast86               653   32       53   2.05
                      Chamilsala65            851   46       93   8.55
                      Chamirrasya33           788   42      181   3.05
                      Chamjask73             1306   66      339  13.83
                      Chanastsda67             66   21        6   3.70
                      Chanirra79              586   23      155   1.01
                      Chanjask65              448   18       68   4.32
                      Chanossast57            446    7      119   4.32
                      Errian63                485   26       94   3.49
                      Eudanu32                451   15      122   2.85
                      Eudanu84                731   22       12   1.02
                      Eusri70                 941   48      294   7.34
                      Frichaststa61           117   21      117   1.79
                      Frichosia58             119   15       87   4.43
                      Frichosiala98           437   24       43   3.54
                      Haisurra41              206   20       78   4.40
                      Hari50                  211   40       37   5.91
                      Heosurnuru52            466   32      292   4.46
                      Heudai45                 81    8      174   3.47
...                                           ...  ...      ...    ...
Male                  Yadanu52                 60   34       44   2.38
                      Yadaphos40              483   60      204   5.35
                      Yalae81                 452   44      201   6.69
                      Yalaeria91              681   33       28   1.06
                      Yaliru88                 59   19      105   3.03
                      Yalo85                  383   34       11   3.65
                      Yalostiphos68           518   29      160   4.40
                      Yarithllodeu72          364   22       88   3.75
                      Yarithrgue83            279   20      163   3.45
                      Yarithsurgue62          231   26      139   4.94
                      Yarolwen77              696   30       87   4.43
                      Yasrisu92                46   27      102   3.44
                      Yastyriaphos75          340   22       41   4.75
                      Yasur35                 257   26      175   4.48
                      Yasur85                 514   21       21   1.10
                      Yathecal72              777   20       67   3.46
                      Yathedeu43              688   44      143   6.02
                      Zhisrisu83              195   20       85   7.89
                      Zontibe81              1019   63      247   8.03
Other / Non-Disclosed Airi27                  637   24      163   3.45
                      Chanosian48             493   70      175   7.52
                      Eodaisu60               242   16       39   3.94
                      Haerithp41               82   16      160   4.40
                      Idairin51               528   40       51   7.00
                      Jiskirran77             228   20       80   3.39
                      Lirtim36                401   15       46   1.33
                      Maluncil97             1178   50      253   5.28
                      Rairith81               350   15       34   2.22
                      Siarithria38            769   76      170   6.91
                      Sundim98                111   21       41   4.75

[576 rows x 4 columns]

In [65]:
Sum_purch_amnt_gender=purch_amnt_gender_and_Indiv.groupby(['Gender']).sum()

In [66]:
Sum_purch_amnt_gender

                       Purchase ID    Age  Item ID    Price
Gender
Female                       42870   2412     9659   361.94
Male                        255921  14942    60978  1967.64
Other / Non-Disclosed         5019    363     1212    50.19

In [67]:
Sum_purch_amnt_gender=Sum_purch_amnt_gender.drop(columns=['Age','Item ID','Purchase ID'])

In [68]:
Sum_purch_amnt_gender

                         Price
Gender
Female                  361.94
Male                   1967.64
Other / Non-Disclosed    50.19

In [69]:
Sum_purch_amnt_gender = Sum_purch_amnt_gender.rename(columns={'Price': 'Total Purchase Value'})

In [70]:
Sum_purch_amnt_gender

                       Total Purchase Value
Gender
Female                               361.94
Male                                1967.64
Other / Non-Disclosed                 50.19

In [71]:
final_gender_table=purch_count_gender.join(purch_average_gender)
final_gender_table=final_gender_table.join(Sum_purch_amnt_gender)
final_gender_table

,Purchase Count,Average Purchase Price,Total Purchase Value
Gender,,,
Female,113,3.203009,361.94
Male,652,3.017853,1967.64
Other / Non-Disclosed,15,3.346000,50.19

In [85]:
gender_counts

                       Total Count  Percentage of Players
Gender
Female                          81               0.140625
Male                           484               0.840278
Other / Non-Disclosed           11               0.019097

In [86]:
final_gender_table['new_counts'] = gender_counts['Total Count']

In [88]:
final_gender_table

,Purchase Count,Average Purchase Price,Total Purchase Value,new_counts
Gender,,,,
Female,113,3.203009,361.94,81
Male,652,3.017853,1967.64,484
Other / Non-Disclosed,15,3.346000,50.19,11

In [89]:
final_gender_table['Avg Total Purchase per Person'] = final_gender_table['Total Purchase Value'] / final_gender_table['new_counts']

In [90]:
final_gender_table

,Purchase Count,Average Purchase Price,Total Purchase Value,new_counts,Avg Total Purchase per Person
Gender,,,,,
Female,113,3.203009,361.94,81,4.468395
Male,652,3.017853,1967.64,484,4.065372
Other / Non-Disclosed,15,3.346000,50.19,11,4.562727

In [91]:
final_gender_table=final_gender_table.drop(columns=['new_counts'])
final_gender_table

,Purchase Count,Average Purchase Price,Total Purchase Value,Avg Total Purchase per Person
Gender,,,,
Female,113,3.203009,361.94,4.468395
Male,652,3.017853,1967.64,4.065372
Other / Non-Disclosed,15,3.346000,50.19,4.562727

In [130]:
bins = [0,9, 14, 19, 24, 29, 34,39,45]
group_names = ["<10", "10-14", "15-19", "20-24", "25-29", "30-34","35-39", "40+"]

In [131]:
purchase_data["Age Group"] = pd.cut(purchase_data["Age"], bins, labels=group_names)

In [132]:
purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Group
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40+
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24
5,5,Yalae81,22,Male,81,Dreamkiss,3.61,20-24
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18,35-39
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67,20-24
8,8,Undjask33,22,Male,21,Souleater,1.10,20-24
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58,35-39
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74,20-24
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67,20-24
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18,20-24
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70,20-24
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86,35-39
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89,20-24
16,16,Lisirra25,20,Male,40,Second Chance,2.52,20-24
17,17,Zontibe81,21,Male,161,Devine,1.76,20-24
18,18,Reunasu60,22,Female,82,Nirvana,4.90,20-24
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64,30-34
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60,20-24
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48,20-24
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81,35-39
23,23,Eyrian71,40,Male,151,Severance,3.40,40+
24,24,Siala43,30,Male,141,Persuasion,3.19,30-34
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,25-29
26,26,Lirtossa84,11,Male,71,Demise,1.61,10-14
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09,<10
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32,20-24
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16,20-24
...,...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61,20-24
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36,10-14
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60,15-19
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,35-39
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05,20-24
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15,10-14
756,756,Ilast79,20,Male,73,Ritual Mace,2.05,20-24
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60,15-19
758,758,Iral74,21,Male,182,Toothpick,4.03,20-24
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77,25-29
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38,20-24
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70,40+
762,762,Asur53,26,Male,110,Suspension,1.44,25-29
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75,20-24
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07,15-19
765,765,Irith83,18,Male,130,Alpha,2.07,15-19
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14,20-24
767,767,Ilmol66,8,Female,92,Final Critic,4.88,<10
768,768,Assassasta79,38,Male,92,Final Critic,4.88,35-39
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58,15-19
770,770,Lirtosia63,34,Male,12,Dawne,1.02,30-34
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35,15-19
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58,25-29
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02,20-24
774,774,Jiskjask80,11,Male,101,Final Critic,4.19,10-14
775,775,Aethedru70,21,Female,60,Wolf,3.54,20-24
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63,20-24
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46,20-24
778,778,Sisur91,7,Male,101,Final Critic,4.19,<10
779,779,Ennrian78,24,Male,50,Dawn,4.60,20-24

In [133]:
age_unique=purchase_data.groupby('SN').first()
age_unique

,Purchase ID,Age,Gender,Item ID,Item Name,Price,Age Group
SN,,,,,,,
Adairialis76,467,16,Male,123,Twilight's Carver,2.28,15-19
Adastirin33,142,35,Female,175,Woeful Adamantite Claymore,4.48,35-39
Aeda94,388,17,Male,128,"Blazeguard, Reach of Eternity",4.91,15-19
Aela59,28,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32,20-24
Aelaria33,630,23,Male,171,Scalpel,1.79,20-24
Aelastirin39,218,23,Male,76,Haunted Bronzed Bludgeon,3.15,20-24
Aelidru27,705,22,Male,183,Dragon's Greatsword,1.09,20-24
Aelin32,52,20,Male,60,Wolf,3.54,20-24
Aelly27,43,24,Male,116,Renewed Skeletal Katana,4.18,20-24
Aellynun67,286,25,Male,153,Mercenary Sabre,3.74,25-29
Aellyria80,746,23,Male,159,"Oathbreaker, Spellblade of Trials",3.08,20-24
Aelollo59,203,33,Male,3,Phantomlight,2.49,30-34
Aenarap34,183,21,Male,15,Soul Infused Crystal,2.96,20-24
Aeral43,263,24,Male,78,"Glimmer, Ender of the Moon",4.40,20-24
Aeral68,674,43,Male,77,"Piety, Guardian of Riddles",4.00,40+
Aeral97,167,23,Male,157,"Spada, Etcher of Hatred",4.80,20-24
Aeralria27,32,10,Male,133,Faith's Scimitar,4.09,10-14
Aeralstical35,583,20,Male,49,"The Oculus, Token of Lost Worlds",2.96,20-24
Aeri84,303,24,Male,71,Demise,1.61,20-24
Aerillorin70,381,16,Male,83,Lifebender,3.33,15-19
Aerithllora36,274,29,Female,82,Nirvana,4.90,25-29
Aerithnucal56,324,15,Male,154,Feral Katana,4.40,15-19
Aerithnuphos61,517,39,Male,128,"Blazeguard, Reach of Eternity",4.91,35-39
Aerithriaphos45,40,20,Male,143,Frenzied Scimitar,1.56,20-24
Aerithriaphos46,236,16,Male,107,"Splitter, Foe Of Subtlety",2.18,15-19
Aesri53,541,31,Male,161,Devine,1.76,30-34
Aesty53,124,21,Male,150,Deathraze,2.85,20-24
Aestysu37,309,25,Male,170,Shadowsteel,3.97,25-29
Aesur96,468,23,Male,30,Stormcaller,2.21,20-24
Aesurstilis64,405,25,Male,70,Hope's End,1.03,25-29
...,...,...,...,...,...,...,...
Undosia27,229,17,Male,72,Winter's Bite,3.77,15-19
Undosian34,90,21,Male,60,Wolf,3.54,20-24
Undotesta33,704,18,Male,95,Singed Onyx Warscythe,4.74,15-19
Wailin72,283,21,Female,9,"Thorn, Conqueror of the Corrupted",2.73,20-24
Yadacal26,337,15,Male,17,"Lazarus, Terror of the Earth",1.70,15-19
Yadaisuir65,625,20,Male,133,Faith's Scimitar,4.09,20-24
Yadam35,553,28,Male,2,Verdict,2.48,25-29
Yadanu52,60,34,Male,44,Bonecarvin Battle Axe,2.38,30-34
Yadaphos40,62,30,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,30-34
Yalae81,5,22,Male,81,Dreamkiss,3.61,20-24
Yalaeria91,681,33,Male,28,"Flux, Destroyer of Due Diligence",1.06,30-34
Yaliru88,59,19,Male,105,Hailstorm Shadowsteel Scythe,3.03,15-19
Yalo85,383,34,Male,11,Brimstone,3.65,30-34
Yalostiphos68,518,29,Male,160,Azurewrath,4.40,25-29
Yana46,280,20,Female,16,Restored Bauble,3.55,20-24
Yarithllodeu72,364,22,Male,88,"Emberling, Defender of Delusions",3.75,20-24
Yarithrgue83,279,20,Male,163,Thunderfury Scimitar,3.45,20-24
Yarithrin84,698,30,Female,58,"Freak's Bite, Favor of Holy Might",4.14,30-34
Yarithsurgue62,231,26,Male,139,"Mercy, Katana of Dismay",4.94,25-29
Yarolwen77,696,30,Male,87,"Deluge, Edge of the West",4.43,30-34
Yasrisu92,46,27,Male,102,Avenger,3.44,25-29
Yastyriaphos75,340,22,Male,41,Orbit,4.75,20-24
Yasur35,257,26,Male,175,Woeful Adamantite Claymore,4.48,25-29
Yasur85,514,21,Male,21,Souleater,1.10,20-24
Yathecal72,777,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46,20-24
Yathecal82,125,20,Female,62,Piece Maker,1.87,20-24
Yathedeu43,93,22,Male,88,"Emberling, Defender of Delusions",3.75,20-24
Yoishirrala98,572,17,Female,145,Fiery Glass Crusader,4.58,15-19
Zhisrisu83,54,10,Male,25,Hero Cane,4.35,10-14
Zontibe81,17,21,Male,161,Devine,1.76,20-24

In [136]:
age_counts=age_unique.groupby(['Age Group']).size().reset_index(name='counts')

In [137]:
age_counts = age_counts.rename(columns={'counts': 'Total Count'})

In [138]:
age_counts

  Age Group  Total Count
0     10-14           22
1     15-19          107
2     20-24          258
3     25-29           77
4     30-34           52
5     35-39           31
6       40+           12
7       <10           17

In [139]:
age_counts['Percentage of Players'] = age_counts['Total Count'] / Unique_user_count

In [140]:
age_counts=age_counts.set_index('Age Group')
age_counts

           Total Count  Percentage of Players
Age Group
10-14               22               0.038194
15-19              107               0.185764
20-24              258               0.447917
25-29               77               0.133681
30-34               52               0.090278
35-39               31               0.053819
40+                 12               0.020833
<10                 17               0.029514

In [109]:
purch_count_age=purchase_data.groupby('Age Group').count()

In [110]:
purch_count_age

           Purchase ID   SN  Age  Gender  Item ID  Item Name  Price
Age Group
<10                 23   23   23      23       23         23     23
10-14               28   28   28      28       28         28     28
15-19              136  136  136     136      136        136    136
20-24              365  365  365     365      365        365    365
25-29              101  101  101     101      101        101    101
30-34               73   73   73      73       73         73     73
35-39               41   41   41      41       41         41     41
40+                 13   13   13      13       13         13     13

In [111]:
purch_count_age=purch_count_age.drop(columns=['SN', 'Age','Item ID','Item Name','Price', 'Gender'])

In [112]:
purch_count_age = purch_count_age.rename(columns={'Purchase ID': 'Purchase Count'})
purch_count_age

           Purchase Count
Age Group
<10                    23
10-14                  28
15-19                 136
20-24                 365
25-29                 101
30-34                  73
35-39                  41
40+                    13

In [113]:
purch_average_age=purchase_data.groupby('Age Group').mean()

In [115]:
purch_average_age=purch_average_age.drop(columns=['Age','Item ID','Purchase ID'])

In [116]:
purch_average_age

              Price
Age Group
<10        3.353478
10-14      2.956429
15-19      3.035956
20-24      3.052219
25-29      2.900990
30-34      2.931507
35-39      3.601707
40+        2.941538

In [141]:
purch_average_age = purch_average_age.rename(columns={'Price': 'Average Purchase Price'})

In [142]:
purch_average_age

           Average Purchase Price
Age Group
<10                      3.353478
10-14                    2.956429
15-19                    3.035956
20-24                    3.052219
25-29                    2.900990
30-34                    2.931507
35-39                    3.601707
40+                      2.941538

In [143]:
purch_total_age=purchase_data.groupby('Age Group').sum()
purch_total_age

           Purchase ID   Age  Item ID    Price
Age Group
<10              10009   181     2437    77.13
10-14            10114   319     2887    82.78
15-19            54859  2284    12798   412.89
20-24           139573  7971    32411  1114.06
25-29            41072  2626     9146   293.00
30-34            26254  2291     6875   214.00
35-39            16596  1505     4137   147.67
40+               5333   540     1158    38.24

In [144]:
purch_total_age=purch_total_age.drop(columns=['Age','Item ID','Purchase ID'])

In [145]:
purch_total_age

             Price
Age Group
<10          77.13
10-14        82.78
15-19       412.89
20-24      1114.06
25-29       293.00
30-34       214.00
35-39       147.67
40+          38.24

In [146]:
purch_total_age = purch_total_age.rename(columns={'Price': 'Total Purchase Value'})

In [147]:
purch_total_age

           Total Purchase Value
Age Group
<10                       77.13
10-14                     82.78
15-19                    412.89
20-24                   1114.06
25-29                    293.00
30-34                    214.00
35-39                    147.67
40+                       38.24

In [150]:
final_age_table=purch_count_age.join(purch_average_age)
final_age_table=final_age_table.join(purch_total_age)
final_age_table

           Purchase Count  Average Purchase Price  Total Purchase Value
Age Group
<10                    23                3.353478                 77.13
10-14                  28                2.956429                 82.78
15-19                 136                3.035956                412.89
20-24                 365                3.052219               1114.06
25-29                 101                2.900990                293.00
30-34                  73                2.931507                214.00
35-39                  41                3.601707                147.67
40+                    13                2.941538                 38.24

In [151]:
final_age_table['new_counts'] = age_counts['Total Count']

In [152]:
final_age_table

,Purchase Count,Average Purchase Price,Total Purchase Value,new_counts
Age Group,,,,
<10,23,3.353478,77.13,17
10-14,28,2.956429,82.78,22
15-19,136,3.035956,412.89,107
20-24,365,3.052219,1114.06,258
25-29,101,2.900990,293.00,77
30-34,73,2.931507,214.00,52
35-39,41,3.601707,147.67,31
40+,13,2.941538,38.24,12

In [153]:
final_age_table['Avg Total Purchase per Person'] = final_age_table['Total Purchase Value'] / final_age_table['new_counts']

In [154]:
final_age_table

,Purchase Count,Average Purchase Price,Total Purchase Value,new_counts,Avg Total Purchase per Person
Age Group,,,,,
<10,23,3.353478,77.13,17,4.537059
10-14,28,2.956429,82.78,22,3.762727
15-19,136,3.035956,412.89,107,3.858785
20-24,365,3.052219,1114.06,258,4.318062
25-29,101,2.900990,293.00,77,3.805195
30-34,73,2.931507,214.00,52,4.115385
35-39,41,3.601707,147.67,31,4.763548
40+,13,2.941538,38.24,12,3.186667

In [155]:
purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Group
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40+
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24

In [156]:
purch_total_indiv=purchase_data.groupby('SN').sum()
purch_total_indiv

                 Purchase ID  Age  Item ID  Price
SN
Adairialis76             467   16      123   2.28
Adastirin33              142   35      175   4.48
Aeda94                   388   17      128   4.91
Aela59                    28   21      119   4.32
Aelaria33                630   23      171   1.79
Aelastirin39             984   46      134   7.29
Aelidru27                705   22      183   1.09
Aelin32                  723   60      326   8.98
Aelly27                  471   48      130   6.79
Aellynun67               286   25      153   3.74
Aellyria80               746   23      159   3.08
Aelollo59                634   66      175   5.63
Aenarap34                183   21       15   2.96
Aeral43                  263   24       78   4.40
Aeral68                  674   43       77   4.00
Aeral97                  167   23      157   4.80
Aeralria27                32   10      133   4.09
Aeralstical35            583   20       49   2.96
Aeri84                   303   24       71   1.61
Aerillorin70             381   16       83   3.33
Aerithllora36            852   58      235   8.64
Aerithnucal56            324   15      154   4.40
Aerithnuphos61           517   39      128   4.91
Aerithriaphos45           40   20      143   1.56
Aerithriaphos46          236   16      107   2.18
Aesri53                  541   31      161   1.76
Aesty53                  377   42      178   3.91
Aestysu37                725   50      183   5.38
Aesur96                  468   23       30   2.21
Aesurstilis64            405   25       70   1.03
...                      ...  ...      ...    ...
Undosia27                229   17       72   3.77
Undosian34               710   42      169   8.30
Undotesta33              704   18       95   4.74
Wailin72                 283   21        9   2.73
Yadacal26                834   30       69   6.54
Yadaisuir65              625   20      133   4.09
Yadam35                  553   28        2   2.48
Yadanu52                  60   34       44   2.38
Yadaphos40               483   60      204   5.35
Yalae81                  452   44      201   6.69
Yalaeria91               681   33       28   1.06
Yaliru88                  59   19      105   3.03
Yalo85                   383   34       11   3.65
Yalostiphos68            518   29      160   4.40
Yana46                   280   20       16   3.55
Yarithllodeu72           364   22       88   3.75
Yarithrgue83             279   20      163   3.45
Yarithrin84              698   30       58   4.14
Yarithsurgue62           231   26      139   4.94
Yarolwen77               696   30       87   4.43
Yasrisu92                 46   27      102   3.44
Yastyriaphos75           340   22       41   4.75
Yasur35                  257   26      175   4.48
Yasur85                  514   21       21   1.10
Yathecal72               777   20       67   3.46
Yathecal82              1400   60      241   6.22
Yathedeu43               688   44      143   6.02
Yoishirrala98            572   17      145   4.58
Zhisrisu83               195   20       85   7.89
Zontibe81               1019   63      247   8.03

[576 rows x 4 columns]

In [157]:
purch_total_indiv=purch_total_indiv.drop(columns=['Age','Item ID','Purchase ID'])
purch_total_indiv.head()

              Price
SN
Adairialis76   2.28
Adastirin33    4.48
Aeda94         4.91
Aela59         4.32
Aelaria33      1.79

In [164]:
#purch_total_indiv.sort_values(['col_1','col_2'])
purch_total_indiv=purch_total_indiv.sort_values(['Price'], ascending=False)
purch_total_indiv
purch_total_indiv['Spend_rank'] = purch_total_indiv['Price'].rank(ascending=0)
purch_total_indiv

               Price  Spend_rank
SN
Lisosia93      18.96         1.0
Idastidru52    15.45         2.0
Chamjask73     13.83         3.0
Iral74         13.62         4.0
Iskadarya95    13.10         5.0
Ilarin91       12.70         6.0
Ialallo29      11.84         7.0
Tyidaim51      11.83         8.0
Lassilsala30   11.51         9.0
Chadolyla44    11.46        10.0
Iri67          11.37        11.0
Inguron55      11.11        12.0
Siallylis44    10.37        13.0
Saistyphos30   10.33        14.0
Phyali88       10.30        15.0
Strithenu87    10.18        16.0
Lisim78        10.02        17.0
Haillyrgue51    9.50        18.5
Phistym51       9.50        18.5
Lamil79         9.29        20.0
Aina42          9.22        21.0
Saesrideu94     9.18        22.0
Arin32          9.09        23.0
Rarallo90       9.05        24.0
Baelollodeu94   9.03        25.0
Aelin32         8.98        26.0
Lisopela58      8.86        27.0
Saedaiphos46    8.83        28.0
Chanastnya43    8.82        29.5
Reunasu60       8.82        29.5
...              ...         ...
Jiskjask85      1.33       545.5
Lirtim36        1.33       545.5
Philodil43      1.29       549.5
Eyista89        1.29       549.5
Mindilsa60      1.28       551.0
Aisur51         1.14       553.5
Ilista82        1.14       553.5
Tyarithn67      1.14       553.5
Jiskimsda56     1.14       553.5
Iduelis31       1.10       558.0
Undjask33       1.10       558.0
Aillyriadru65   1.10       558.0
Yasur85         1.10       558.0
Eryon48         1.10       558.0
Aelidru27       1.09       561.5
Lirtassa52      1.09       561.5
Yalaeria91      1.06       563.0
Saida58         1.03       565.0
Euthe35         1.03       565.0
Aesurstilis64   1.03       565.0
Isurria36       1.02       570.0
Irilis75        1.02       570.0
Ililsasya43     1.02       570.0
Eudanu84        1.02       570.0
Hala31          1.02       570.0
Qilalista41     1.02       570.0
Frichjaskan98   1.02       570.0
Chanirra79      1.01       574.5
Aidai61         1.01       574.5
Alo38           1.00       576.0

[576 rows x 2 columns]

In [165]:
purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Group
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40+
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24

In [167]:
purch_total_indiv.reset_index()

                SN  Price  Spend_rank
0        Lisosia93  18.96         1.0
1      Idastidru52  15.45         2.0
2       Chamjask73  13.83         3.0
3           Iral74  13.62         4.0
4      Iskadarya95  13.10         5.0
5         Ilarin91  12.70         6.0
6        Ialallo29  11.84         7.0
7        Tyidaim51  11.83         8.0
8     Lassilsala30  11.51         9.0
9      Chadolyla44  11.46        10.0
10           Iri67  11.37        11.0
11       Inguron55  11.11        12.0
12     Siallylis44  10.37        13.0
13    Saistyphos30  10.33        14.0
14        Phyali88  10.30        15.0
15     Strithenu87  10.18        16.0
16         Lisim78  10.02        17.0
17    Haillyrgue51   9.50        18.5
18       Phistym51   9.50        18.5
19         Lamil79   9.29        20.0
20          Aina42   9.22        21.0
21     Saesrideu94   9.18        22.0
22          Arin32   9.09        23.0
23       Rarallo90   9.05        24.0
24   Baelollodeu94   9.03        25.0
25         Aelin32   8.98        26.0
26      Lisopela58   8.86        27.0
27    Saedaiphos46   8.83        28.0
28    Chanastnya43   8.82        29.5
29       Reunasu60   8.82        29.5
..             ...    ...         ...
546     Jiskjask85   1.33       545.5
547       Lirtim36   1.33       545.5
548     Philodil43   1.29       549.5
549       Eyista89   1.29       549.5
550     Mindilsa60   1.28       551.0
551        Aisur51   1.14       553.5
552       Ilista82   1.14       553.5
553     Tyarithn67   1.14       553.5
554    Jiskimsda56   1.14       553.5
555      Iduelis31   1.10       558.0
556      Undjask33   1.10       558.0
557  Aillyriadru65   1.10       558.0
558        Yasur85   1.10       558.0
559        Eryon48   1.10       558.0
560      Aelidru27   1.09       561.5
561     Lirtassa52   1.09       561.5
562     Yalaeria91   1.06       563.0
563        Saida58   1.03       565.0
564        Euthe35   1.03       565.0
565  Aesurstilis64   1.03       565.0
566      Isurria36   1.02       570.0
567       Irilis75   1.02       570.0
568    Ililsasya43   1.02       570.0
569       Eudanu84   1.02       570.0
570         Hala31   1.02       570.0
571    Qilalista41   1.02       570.0
572  Frichjaskan98   1.02       570.0
573     Chanirra79   1.01       574.5
574        Aidai61   1.01       574.5
575          Alo38   1.00       576.0

[576 rows x 3 columns]

In [175]:
merge_table = pd.merge(purchase_data, purch_total_indiv, on="SN")
merge_table

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price_x,Age Group,Price_y,Spend_rank
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24,10.02,17.0
1,67,Lisim78,20,Male,138,"Peacekeeper, Wit of Dark Magic",4.74,20-24,10.02,17.0
2,245,Lisim78,20,Male,85,Malificent Bag,1.75,20-24,10.02,17.0
3,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40+,1.56,525.0
4,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24,4.88,149.5
5,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24,3.27,347.0
6,4,Iskosia90,23,Male,131,Fury,1.44,20-24,1.44,538.0
7,5,Yalae81,22,Male,81,Dreamkiss,3.61,20-24,6.69,75.5
8,447,Yalae81,22,Male,120,Agatha,3.08,20-24,6.69,75.5
9,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18,35-39,2.18,454.0
10,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67,20-24,4.42,192.0
11,168,Iskjaskst81,20,Male,85,Malificent Bag,1.75,20-24,4.42,192.0
12,8,Undjask33,22,Male,21,Souleater,1.10,20-24,1.10,558.0
13,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58,35-39,7.52,53.5
14,484,Chanosian48,35,Other / Non-Disclosed,39,"Betrayal, Whisper of Grieving Widows",3.94,35-39,7.52,53.5
15,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74,20-24,11.11,12.0
16,132,Inguron55,23,Male,145,Fiery Glass Crusader,4.58,20-24,11.11,12.0
17,509,Inguron55,23,Male,117,"Heartstriker, Legacy of the Light",1.79,20-24,11.11,12.0
18,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67,20-24,6.86,70.0
19,99,Haisrisuir60,23,Male,101,Final Critic,4.19,20-24,6.86,70.0
20,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18,20-24,6.36,87.0
21,50,Saelaephos52,21,Male,22,Amnesia,2.18,20-24,6.36,87.0
22,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70,20-24,1.70,510.0
23,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86,35-39,9.18,22.0
24,264,Saesrideu94,35,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32,35-39,9.18,22.0
25,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89,20-24,2.89,401.0
26,16,Lisirra25,20,Male,40,Second Chance,2.52,20-24,2.52,420.5
27,17,Zontibe81,21,Male,161,Devine,1.76,20-24,8.03,44.0
28,442,Zontibe81,21,Male,84,Arcane Gem,3.79,20-24,8.03,44.0
29,560,Zontibe81,21,Male,2,Verdict,2.48,20-24,8.03,44.0
...,...,...,...,...,...,...,...,...,...,...
750,728,Chanosiaya39,44,Male,93,Apocalyptic Battlescythe,1.97,40+,1.97,477.0
751,729,Assylla81,20,Male,74,Yearning Crusher,4.18,20-24,4.18,244.5
752,730,Aidaira26,30,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,30-34,4.23,233.5
753,731,Eudanu84,22,Female,12,Dawne,1.02,20-24,1.02,570.0
754,733,Chamiman85,20,Male,66,Victor Iron Spikes,4.40,20-24,4.40,200.0
755,736,Tyialisti80,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14,20-24,4.14,248.5
756,737,Marundi65,22,Male,149,"Tranquility, Razor of Black Magic",1.75,20-24,1.75,501.0
757,738,Eusur90,36,Male,121,Massacre,1.60,35-39,1.60,522.0
758,739,Mindirranya33,35,Male,61,Ragnarok,3.87,35-39,3.87,270.0
759,741,Phiallylis33,19,Male,145,Fiery Glass Crusader,4.58,15-19,4.58,173.5
760,742,Isty55,20,Male,5,Putrid Fan,4.08,20-24,4.08,253.0
761,743,Frichilsa31,15,Male,110,Suspension,1.44,15-19,1.44,538.0
762,745,Chanista95,39,Male,37,"Shadow Strike, Glory of Ending Hope",3.16,35-39,3.16,359.5
763,746,Aellyria80,23,Male,159,"Oathbreaker, Spellblade of Trials",3.08,20-24,3.08,377.0
764,748,Rastynusuir31,20,Male,55,Vindictive Glass Edge,2.27,20-24,2.27,442.5
765,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61,20-24,3.61,295.5
766,751,Lisjaskan36,11,Male,180,Stormcaller,3.36,10-14,3.36,339.0
767,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60,15-19,2.60,418.5
768,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,35-39,4.23,233.5
769,756,Ilast79,20,Male,73,Ritual Mace,2.05,20-24,2.05,466.0
770,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60,15-19,4.60,168.5
771,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70,40+,1.70,510.0
772,765,Irith83,18,Male,130,Alpha,2.07,15-19,2.07,460.0
773,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58,15-19,4.58,173.5
774,771,Iskossasda43,16,Male,25,Hero Cane,4.35,15-19,4.35,213.0
775,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02,20-24,1.02,570.0
776,774,Jiskjask80,11,Male,101,Final Critic,4.19,10-14,4.19,240.5
777,775,Aethedru70,21,Female,60,Wolf,3.54,20-24,3.54,303.0
778,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46,20-24,3.46,318.0
779,778,Sisur91,7,Male,101,Final Critic,4.19,<10,4.19,240.5

In [177]:
# Create variable with TRUE if age is greater than 50
top_five =merge_table['Spend_rank'] < 6


sub_set=merge_table[top_five]

In [178]:
sub_set

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price_x,Age Group,Price_y,Spend_rank
113,74,Lisosia93,25,Male,89,"Blazefury, Protector of Delusions",4.64,25-29,18.96,1.0
114,120,Lisosia93,25,Male,24,Warped Fetish,3.81,25-29,18.96,1.0
115,224,Lisosia93,25,Male,157,"Spada, Etcher of Hatred",4.80,25-29,18.96,1.0
116,603,Lisosia93,25,Male,141,Persuasion,3.19,25-29,18.96,1.0
117,609,Lisosia93,25,Male,40,Second Chance,2.52,25-29,18.96,1.0
191,128,Iral74,21,Male,58,"Freak's Bite, Favor of Holy Might",4.14,20-24,13.62,4.0
192,623,Iral74,21,Male,114,Yearning Mageblade,3.82,20-24,13.62,4.0
193,758,Iral74,21,Male,182,Toothpick,4.03,20-24,13.62,4.0
194,776,Iral74,21,Male,164,Exiled Doomblade,1.63,20-24,13.62,4.0
215,148,Iskadarya95,20,Male,148,"Warmonger, Gift of Suffering's End",4.03,20-24,13.10,5.0
216,247,Iskadarya95,20,Male,82,Nirvana,4.90,20-24,13.10,5.0
217,318,Iskadarya95,20,Male,91,Celeste,4.17,20-24,13.10,5.0
311,222,Chamjask73,22,Female,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,20-24,13.83,3.0
312,520,Chamjask73,22,Female,109,"Downfall, Scalpel Of The Emperor",4.76,20-24,13.83,3.0
313,564,Chamjask73,22,Female,52,Hatred,4.84,20-24,13.83,3.0
380,290,Idastidru52,24,Male,147,"Hellreaver, Heirloom of Inception",4.93,20-24,15.45,2.0
381,490,Idastidru52,24,Male,148,"Warmonger, Gift of Suffering's End",4.03,20-24,15.45,2.0
382,543,Idastidru52,24,Male,121,Massacre,1.60,20-24,15.45,2.0
383,676,Idastidru52,24,Male,111,Misery's End,4.89,20-24,15.45,2.0

In [183]:
top_indiv_count=sub_set.groupby('SN').count()
top_indiv_count

,Purchase ID,Age,Gender,Item ID,Item Name,Price_x,Age Group,Price_y,Spend_rank
SN,,,,,,,,,
Chamjask73,3,3,3,3,3,3,3,3,3
Idastidru52,4,4,4,4,4,4,4,4,4
Iral74,4,4,4,4,4,4,4,4,4
Iskadarya95,3,3,3,3,3,3,3,3,3
Lisosia93,5,5,5,5,5,5,5,5,5

In [184]:
top_indiv_count=top_indiv_count.drop(columns=['Age','Item ID','Gender', 'Item Name', 'Price_x', 'Price_y', 'Spend_rank','Age Group'])
top_indiv_count.head()

             Purchase ID
SN
Chamjask73             3
Idastidru52            4
Iral74                 4
Iskadarya95            3
Lisosia93              5

In [185]:
top_indiv_count = top_indiv_count.rename(columns={'Purchase ID': 'Purchase Count'})
top_indiv_count

             Purchase Count
SN
Chamjask73                3
Idastidru52               4
Iral74                    4
Iskadarya95               3
Lisosia93                 5

In [190]:
top_indiv_mean_value=sub_set.groupby('SN').mean()
top_indiv_mean_value

             Purchase ID   Age  Item ID   Price_x  Price_y  Spend_rank
SN
Chamjask73    435.333333  22.0   113.00  4.610000    13.83         3.0
Idastidru52   499.750000  24.0   131.75  3.862500    15.45         2.0
Iral74        571.250000  21.0   129.50  3.405000    13.62         4.0
Iskadarya95   237.666667  20.0   107.00  4.366667    13.10         5.0
Lisosia93     326.000000  25.0    90.20  3.792000    18.96         1.0

In [191]:
top_indiv_mean_value=top_indiv_mean_value.drop(columns=['Age','Item ID','Purchase ID', 'Price_y', 'Spend_rank'])
top_indiv_mean_value.head()

              Price_x
SN
Chamjask73   4.610000
Idastidru52  3.862500
Iral74       3.405000
Iskadarya95  4.366667
Lisosia93    3.792000

In [192]:
top_indiv_mean_value = top_indiv_mean_value.rename(columns={'Price_x': 'Average Purchase Price'})
top_indiv_mean_value

             Average Purchase Price
SN
Chamjask73                 4.610000
Idastidru52                3.862500
Iral74                     3.405000
Iskadarya95                4.366667
Lisosia93                  3.792000

In [193]:
top_indiv_spend=sub_set.groupby('SN').first()
top_indiv_spend

,Purchase ID,Age,Gender,Item ID,Item Name,Price_x,Age Group,Price_y,Spend_rank
SN,,,,,,,,,
Chamjask73,222,22,Female,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,20-24,13.83,3.0
Idastidru52,290,24,Male,147,"Hellreaver, Heirloom of Inception",4.93,20-24,15.45,2.0
Iral74,128,21,Male,58,"Freak's Bite, Favor of Holy Might",4.14,20-24,13.62,4.0
Iskadarya95,148,20,Male,148,"Warmonger, Gift of Suffering's End",4.03,20-24,13.10,5.0
Lisosia93,74,25,Male,89,"Blazefury, Protector of Delusions",4.64,25-29,18.96,1.0

In [195]:
top_indiv_spend=top_indiv_spend.drop(columns=['Age','Purchase ID','Gender','Item ID','Item Name','Age Group','Purchase ID', 'Price_x', 'Spend_rank'])
top_indiv_spend.head()

             Price_y
SN
Chamjask73     13.83
Idastidru52    15.45
Iral74         13.62
Iskadarya95    13.10
Lisosia93      18.96

In [196]:
top_indiv_spend = top_indiv_spend.rename(columns={'Price_y': 'Total Purchase Value'})
top_indiv_spend

             Total Purchase Value
SN
Chamjask73                  13.83
Idastidru52                 15.45
Iral74                      13.62
Iskadarya95                 13.10
Lisosia93                   18.96

In [197]:
final_top_spend_table=top_indiv_count.join(top_indiv_mean_value)
final_top_spend_table=final_top_spend_table.join(top_indiv_spend)
final_top_spend_table

             Purchase Count  Average Purchase Price  Total Purchase Value
SN
Chamjask73                3                4.610000                 13.83
Idastidru52               4                3.862500                 15.45
Iral74                    4                3.405000                 13.62
Iskadarya95               3                4.366667                 13.10
Lisosia93                 5                3.792000                 18.96

In [198]:
final_top_spend_table=final_top_spend_table.sort_values(['Total Purchase Value'], ascending=False)
final_top_spend_table

             Purchase Count  Average Purchase Price  Total Purchase Value
SN
Lisosia93                 5                3.792000                 18.96
Idastidru52               4                3.862500                 15.45
Chamjask73                3                4.610000                 13.83
Iral74                    4                3.405000                 13.62
Iskadarya95               3                4.366667                 13.10

In [200]:
popular_subset=purchase_data.drop(columns=['SN','Age','Purchase ID','Gender','Age Group','Purchase ID'])
popular_subset.head()

   Item ID                                  Item Name  Price
0      108  Extraction, Quickblade Of Trembling Hands   3.53
1      143                          Frenzied Scimitar   1.56
2       92                               Final Critic   4.88
3      100                                Blindscythe   3.27
4      131                                       Fury   1.44

In [202]:
popular_subset_total_sold=popular_subset.groupby(['Item ID', 'Item Name']).count()
popular_subset_total_sold

                                                      Price
Item ID Item Name
0       Splinter                                          4
1       Crucifer                                          3
2       Verdict                                           6
3       Phantomlight                                      6
4       Bloodlord's Fetish                                5
5       Putrid Fan                                        4
6       Rusty Skull                                       2
7       Thorn, Satchel of Dark Souls                      7
8       Purgatory, Gem of Regret                          3
9       Thorn, Conqueror of the Corrupted                 4
10      Sleepwalker                                       4
11      Brimstone                                         5
12      Dawne                                             6
13      Serenity                                          4
14      Possessed Core                                    2
15      Soul Infused Crystal                              5
16      Restored Bauble                                   4
17      Lazarus, Terror of the Earth                      4
18      Torchlight, Bond of Storms                        2
19      Pursuit, Cudgel of Necromancy                     8
20      Netherbane                                        5
21      Souleater                                         5
22      Amnesia                                           6
23      Crucifer                                          1
24      Warped Fetish                                     5
25      Hero Cane                                         6
26      Unholy Wand                                       2
27      Riddle, Tribute of Ended Dreams                   1
28      Flux, Destroyer of Due Diligence                  2
29      Chaos, Ender of the End                           5
...                                                     ...
154     Feral Katana                                      4
155     War-Forged Gold Deflector                         5
156     Soul-Forged Steel Shortsword                      5
157     Spada, Etcher of Hatred                           4
158     Darkheart, Butcher of the Champion                2
159     Oathbreaker, Spellblade of Trials                 7
160     Azurewrath                                        6
161     Devine                                            5
162     Abyssal Shard                                     5
163     Thunderfury Scimitar                              5
164     Exiled Doomblade                                  7
165     Bone Crushing Silver Skewer                       4
166     Thirsty Iron Reaver                               3
167     Malice, Legacy of the Queen                       4
168     Sun Strike, Jaws of Twisted Visions               2
169     Interrogator, Blood Blade of the Queen            4
170     Shadowsteel                                       4
171     Scalpel                                           3
172     Blade of the Grave                                4
173     Stormfury Longsword                               2
174     Primitive Blade                                   4
175     Woeful Adamantite Claymore                        3
176     Relentless Iron Skewer                            2
177     Winterthorn, Defender of Shifting Worlds          2
178     Oathbreaker, Last Hope of the Breaking Storm     12
179     Wolf, Promise of the Moonwalker                   6
180     Stormcaller                                       1
181     Reaper's Toll                                     5
182     Toothpick                                         3
183     Dragon's Greatsword                               3

[183 rows x 1 columns]

In [204]:
popular_subset_total_sold = popular_subset_total_sold.rename(columns={'Price': 'Purchase Count'})
popular_subset_total_sold

                                                      Purchase Count
Item ID Item Name
0       Splinter                                                   4
1       Crucifer                                                   3
2       Verdict                                                    6
3       Phantomlight                                               6
4       Bloodlord's Fetish                                         5
5       Putrid Fan                                                 4
6       Rusty Skull                                                2
7       Thorn, Satchel of Dark Souls                               7
8       Purgatory, Gem of Regret                                   3
9       Thorn, Conqueror of the Corrupted                          4
10      Sleepwalker                                                4
11      Brimstone                                                  5
12      Dawne                                                      6
13      Serenity                                                   4
14      Possessed Core                                             2
15      Soul Infused Crystal                                       5
16      Restored Bauble                                            4
17      Lazarus, Terror of the Earth                               4
18      Torchlight, Bond of Storms                                 2
19      Pursuit, Cudgel of Necromancy                              8
20      Netherbane                                                 5
21      Souleater                                                  5
22      Amnesia                                                    6
23      Crucifer                                                   1
24      Warped Fetish                                              5
25      Hero Cane                                                  6
26      Unholy Wand                                                2
27      Riddle, Tribute of Ended Dreams                            1
28      Flux, Destroyer of Due Diligence                           2
29      Chaos, Ender of the End                                    5
...                                                              ...
154     Feral Katana                                               4
155     War-Forged Gold Deflector                                  5
156     Soul-Forged Steel Shortsword                               5
157     Spada, Etcher of Hatred                                    4
158     Darkheart, Butcher of the Champion                         2
159     Oathbreaker, Spellblade of Trials                          7
160     Azurewrath                                                 6
161     Devine                                                     5
162     Abyssal Shard                                              5
163     Thunderfury Scimitar                                       5
164     Exiled Doomblade                                           7
165     Bone Crushing Silver Skewer                                4
166     Thirsty Iron Reaver                                        3
167     Malice, Legacy of the Queen                                4
168     Sun Strike, Jaws of Twisted Visions                        2
169     Interrogator, Blood Blade of the Queen                     4
170     Shadowsteel                                                4
171     Scalpel                                                    3
172     Blade of the Grave                                         4
173     Stormfury Longsword                                        2
174     Primitive Blade                                            4
175     Woeful Adamantite Claymore                                 3
176     Relentless Iron Skewer                                     2
177     Winterthorn, Defender of Shifting Worlds                   2
178     Oathbreaker, Last Hope of the Breaking Storm              12
179     Wolf, Promise of the Moonwalker                            6
180     Stormcaller                                                1
181     Reaper's Toll                                              5
182     Toothpick                                                  3
183     Dragon's Greatsword                                        3

[183 rows x 1 columns]

In [205]:
popular_subset_item_price=popular_subset.groupby(['Item ID', 'Item Name']).first()
popular_subset_item_price

                                                      Price
Item ID Item Name
0       Splinter                                       1.28
1       Crucifer                                       3.26
2       Verdict                                        2.48
3       Phantomlight                                   2.49
4       Bloodlord's Fetish                             1.70
5       Putrid Fan                                     4.08
6       Rusty Skull                                    3.70
7       Thorn, Satchel of Dark Souls                   1.33
8       Purgatory, Gem of Regret                       3.93
9       Thorn, Conqueror of the Corrupted              2.73
10      Sleepwalker                                    1.79
11      Brimstone                                      3.65
12      Dawne                                          1.02
13      Serenity                                       1.41
14      Possessed Core                                 2.61
15      Soul Infused Crystal                           2.96
16      Restored Bauble                                3.55
17      Lazarus, Terror of the Earth                   1.70
18      Torchlight, Bond of Storms                     4.65
19      Pursuit, Cudgel of Necromancy                  1.02
20      Netherbane                                     3.27
21      Souleater                                      1.10
22      Amnesia                                        2.18
23      Crucifer                                       1.99
24      Warped Fetish                                  3.81
25      Hero Cane                                      4.35
26      Unholy Wand                                    1.12
27      Riddle, Tribute of Ended Dreams                3.30
28      Flux, Destroyer of Due Diligence               1.06
29      Chaos, Ender of the End                        1.98
...                                                     ...
154     Feral Katana                                   4.40
155     War-Forged Gold Deflector                      1.01
156     Soul-Forged Steel Shortsword                   1.77
157     Spada, Etcher of Hatred                        4.80
158     Darkheart, Butcher of the Champion             2.45
159     Oathbreaker, Spellblade of Trials              3.08
160     Azurewrath                                     4.40
161     Devine                                         1.76
162     Abyssal Shard                                  2.67
163     Thunderfury Scimitar                           3.45
164     Exiled Doomblade                               1.63
165     Bone Crushing Silver Skewer                    4.86
166     Thirsty Iron Reaver                            3.07
167     Malice, Legacy of the Queen                    3.61
168     Sun Strike, Jaws of Twisted Visions            1.48
169     Interrogator, Blood Blade of the Queen         2.18
170     Shadowsteel                                    3.97
171     Scalpel                                        1.79
172     Blade of the Grave                             3.14
173     Stormfury Longsword                            4.93
174     Primitive Blade                                3.47
175     Woeful Adamantite Claymore                     4.48
176     Relentless Iron Skewer                         2.84
177     Winterthorn, Defender of Shifting Worlds       2.08
178     Oathbreaker, Last Hope of the Breaking Storm   4.23
179     Wolf, Promise of the Moonwalker                4.48
180     Stormcaller                                    3.36
181     Reaper's Toll                                  1.66
182     Toothpick                                      4.03
183     Dragon's Greatsword                            1.09

[183 rows x 1 columns]

In [206]:
popular_subset_item_price = popular_subset_item_price.rename(columns={'Price': 'Item Price'})
popular_subset_item_price

                                                      Item Price
Item ID Item Name
0       Splinter                                            1.28
1       Crucifer                                            3.26
2       Verdict                                             2.48
3       Phantomlight                                        2.49
4       Bloodlord's Fetish                                  1.70
5       Putrid Fan                                          4.08
6       Rusty Skull                                         3.70
7       Thorn, Satchel of Dark Souls                        1.33
8       Purgatory, Gem of Regret                            3.93
9       Thorn, Conqueror of the Corrupted                   2.73
10      Sleepwalker                                         1.79
11      Brimstone                                           3.65
12      Dawne                                               1.02
13      Serenity                                            1.41
14      Possessed Core                                      2.61
15      Soul Infused Crystal                                2.96
16      Restored Bauble                                     3.55
17      Lazarus, Terror of the Earth                        1.70
18      Torchlight, Bond of Storms                          4.65
19      Pursuit, Cudgel of Necromancy                       1.02
20      Netherbane                                          3.27
21      Souleater                                           1.10
22      Amnesia                                             2.18
23      Crucifer                                            1.99
24      Warped Fetish                                       3.81
25      Hero Cane                                           4.35
26      Unholy Wand                                         1.12
27      Riddle, Tribute of Ended Dreams                     3.30
28      Flux, Destroyer of Due Diligence                    1.06
29      Chaos, Ender of the End                             1.98
...                                                          ...
154     Feral Katana                                        4.40
155     War-Forged Gold Deflector                           1.01
156     Soul-Forged Steel Shortsword                        1.77
157     Spada, Etcher of Hatred                             4.80
158     Darkheart, Butcher of the Champion                  2.45
159     Oathbreaker, Spellblade of Trials                   3.08
160     Azurewrath                                          4.40
161     Devine                                              1.76
162     Abyssal Shard                                       2.67
163     Thunderfury Scimitar                                3.45
164     Exiled Doomblade                                    1.63
165     Bone Crushing Silver Skewer                         4.86
166     Thirsty Iron Reaver                                 3.07
167     Malice, Legacy of the Queen                         3.61
168     Sun Strike, Jaws of Twisted Visions                 1.48
169     Interrogator, Blood Blade of the Queen              2.18
170     Shadowsteel                                         3.97
171     Scalpel                                             1.79
172     Blade of the Grave                                  3.14
173     Stormfury Longsword                                 4.93
174     Primitive Blade                                     3.47
175     Woeful Adamantite Claymore                          4.48
176     Relentless Iron Skewer                              2.84
177     Winterthorn, Defender of Shifting Worlds            2.08
178     Oathbreaker, Last Hope of the Breaking Storm        4.23
179     Wolf, Promise of the Moonwalker                     4.48
180     Stormcaller                                         3.36
181     Reaper's Toll                                       1.66
182     Toothpick                                           4.03
183     Dragon's Greatsword                                 1.09

[183 rows x 1 columns]

In [207]:
popular_subset_item_toal=popular_subset.groupby(['Item ID', 'Item Name']).sum()
popular_subset_item_toal

                                                      Price
Item ID Item Name
0       Splinter                                       5.12
1       Crucifer                                       9.78
2       Verdict                                       14.88
3       Phantomlight                                  14.94
4       Bloodlord's Fetish                             8.50
5       Putrid Fan                                    16.32
6       Rusty Skull                                    7.40
7       Thorn, Satchel of Dark Souls                   9.31
8       Purgatory, Gem of Regret                      11.79
9       Thorn, Conqueror of the Corrupted             10.92
10      Sleepwalker                                    7.16
11      Brimstone                                     18.25
12      Dawne                                          6.12
13      Serenity                                       5.64
14      Possessed Core                                 5.22
15      Soul Infused Crystal                          14.80
16      Restored Bauble                               14.20
17      Lazarus, Terror of the Earth                   6.80
18      Torchlight, Bond of Storms                     9.30
19      Pursuit, Cudgel of Necromancy                  8.16
20      Netherbane                                    16.35
21      Souleater                                      5.50
22      Amnesia                                       13.08
23      Crucifer                                       1.99
24      Warped Fetish                                 19.05
25      Hero Cane                                     26.10
26      Unholy Wand                                    2.24
27      Riddle, Tribute of Ended Dreams                3.30
28      Flux, Destroyer of Due Diligence               2.12
29      Chaos, Ender of the End                        9.90
...                                                     ...
154     Feral Katana                                  17.60
155     War-Forged Gold Deflector                      5.05
156     Soul-Forged Steel Shortsword                   8.85
157     Spada, Etcher of Hatred                       19.20
158     Darkheart, Butcher of the Champion             4.90
159     Oathbreaker, Spellblade of Trials             21.56
160     Azurewrath                                    26.40
161     Devine                                         8.80
162     Abyssal Shard                                 13.35
163     Thunderfury Scimitar                          17.25
164     Exiled Doomblade                              11.41
165     Bone Crushing Silver Skewer                   19.44
166     Thirsty Iron Reaver                            9.21
167     Malice, Legacy of the Queen                   14.44
168     Sun Strike, Jaws of Twisted Visions            2.96
169     Interrogator, Blood Blade of the Queen         8.72
170     Shadowsteel                                   15.88
171     Scalpel                                        5.37
172     Blade of the Grave                            12.56
173     Stormfury Longsword                            9.86
174     Primitive Blade                               13.88
175     Woeful Adamantite Claymore                    13.44
176     Relentless Iron Skewer                         5.68
177     Winterthorn, Defender of Shifting Worlds       4.16
178     Oathbreaker, Last Hope of the Breaking Storm  50.76
179     Wolf, Promise of the Moonwalker               26.88
180     Stormcaller                                    3.36
181     Reaper's Toll                                  8.30
182     Toothpick                                     12.09
183     Dragon's Greatsword                            3.27

[183 rows x 1 columns]

In [208]:
popular_subset_item_toal = popular_subset_item_toal.rename(columns={'Price': 'Total Purchase Value'})
popular_subset_item_toal

                                                      Total Purchase Value
Item ID Item Name
0       Splinter                                                      5.12
1       Crucifer                                                      9.78
2       Verdict                                                      14.88
3       Phantomlight                                                 14.94
4       Bloodlord's Fetish                                            8.50
5       Putrid Fan                                                   16.32
6       Rusty Skull                                                   7.40
7       Thorn, Satchel of Dark Souls                                  9.31
8       Purgatory, Gem of Regret                                     11.79
9       Thorn, Conqueror of the Corrupted                            10.92
10      Sleepwalker                                                   7.16
11      Brimstone                                                    18.25
12      Dawne                                                         6.12
13      Serenity                                                      5.64
14      Possessed Core                                                5.22
15      Soul Infused Crystal                                         14.80
16      Restored Bauble                                              14.20
17      Lazarus, Terror of the Earth                                  6.80
18      Torchlight, Bond of Storms                                    9.30
19      Pursuit, Cudgel of Necromancy                                 8.16
20      Netherbane                                                   16.35
21      Souleater                                                     5.50
22      Amnesia                                                      13.08
23      Crucifer                                                      1.99
24      Warped Fetish                                                19.05
25      Hero Cane                                                    26.10
26      Unholy Wand                                                   2.24
27      Riddle, Tribute of Ended Dreams                               3.30
28      Flux, Destroyer of Due Diligence                              2.12
29      Chaos, Ender of the End                                       9.90
...                                                                    ...
154     Feral Katana                                                 17.60
155     War-Forged Gold Deflector                                     5.05
156     Soul-Forged Steel Shortsword                                  8.85
157     Spada, Etcher of Hatred                                      19.20
158     Darkheart, Butcher of the Champion                            4.90
159     Oathbreaker, Spellblade of Trials                            21.56
160     Azurewrath                                                   26.40
161     Devine                                                        8.80
162     Abyssal Shard                                                13.35
163     Thunderfury Scimitar                                         17.25
164     Exiled Doomblade                                             11.41
165     Bone Crushing Silver Skewer                                  19.44
166     Thirsty Iron Reaver                                           9.21
167     Malice, Legacy of the Queen                                  14.44
168     Sun Strike, Jaws of Twisted Visions                           2.96
169     Interrogator, Blood Blade of the Queen                        8.72
170     Shadowsteel                                                  15.88
171     Scalpel                                                       5.37
172     Blade of the Grave                                           12.56
173     Stormfury Longsword                                           9.86
174     Primitive Blade                                              13.88
175     Woeful Adamantite Claymore                                   13.44
176     Relentless Iron Skewer                                        5.68
177     Winterthorn, Defender of Shifting Worlds                      4.16
178     Oathbreaker, Last Hope of the Breaking Storm                 50.76
179     Wolf, Promise of the Moonwalker                              26.88
180     Stormcaller                                                   3.36
181     Reaper's Toll                                                 8.30
182     Toothpick                                                    12.09
183     Dragon's Greatsword                                           3.27

[183 rows x 1 columns]

In [209]:
final_popular_table=popular_subset_total_sold.join(popular_subset_item_price)
final_popular_table=final_popular_table.join(popular_subset_item_toal)

final_popular_table

,,Purchase Count,Item Price,Total Purchase Value
Item ID,Item Name,,,
0,Splinter,4,1.28,5.12
1,Crucifer,3,3.26,9.78
2,Verdict,6,2.48,14.88
3,Phantomlight,6,2.49,14.94
4,Bloodlord's Fetish,5,1.70,8.50
5,Putrid Fan,4,4.08,16.32
6,Rusty Skull,2,3.70,7.40
7,"Thorn, Satchel of Dark Souls",7,1.33,9.31
8,"Purgatory, Gem of Regret",3,3.93,11.79
9,"Thorn, Conqueror of the Corrupted",4,2.73,10.92
10,Sleepwalker,4,1.79,7.16
11,Brimstone,5,3.65,18.25
12,Dawne,6,1.02,6.12
13,Serenity,4,1.41,5.64
14,Possessed Core,2,2.61,5.22
15,Soul Infused Crystal,5,2.96,14.80
16,Restored Bauble,4,3.55,14.20
17,"Lazarus, Terror of the Earth",4,1.70,6.80
18,"Torchlight, Bond of Storms",2,4.65,9.30
19,"Pursuit, Cudgel of Necromancy",8,1.02,8.16
20,Netherbane,5,3.27,16.35
21,Souleater,5,1.10,5.50
22,Amnesia,6,2.18,13.08
23,Crucifer,1,1.99,1.99
24,Warped Fetish,5,3.81,19.05
25,Hero Cane,6,4.35,26.10
26,Unholy Wand,2,1.12,2.24
27,"Riddle, Tribute of Ended Dreams",1,3.30,3.30
28,"Flux, Destroyer of Due Diligence",2,1.06,2.12
29,"Chaos, Ender of the End",5,1.98,9.90
...,...,...,...,...
154,Feral Katana,4,4.40,17.60
155,War-Forged Gold Deflector,5,1.01,5.05
156,Soul-Forged Steel Shortsword,5,1.77,8.85
157,"Spada, Etcher of Hatred",4,4.80,19.20
158,"Darkheart, Butcher of the Champion",2,2.45,4.90
159,"Oathbreaker, Spellblade of Trials",7,3.08,21.56
160,Azurewrath,6,4.40,26.40
161,Devine,5,1.76,8.80
162,Abyssal Shard,5,2.67,13.35
163,Thunderfury Scimitar,5,3.45,17.25
164,Exiled Doomblade,7,1.63,11.41
165,Bone Crushing Silver Skewer,4,4.86,19.44
166,Thirsty Iron Reaver,3,3.07,9.21
167,"Malice, Legacy of the Queen",4,3.61,14.44
168,"Sun Strike, Jaws of Twisted Visions",2,1.48,2.96
169,"Interrogator, Blood Blade of the Queen",4,2.18,8.72
170,Shadowsteel,4,3.97,15.88
171,Scalpel,3,1.79,5.37
172,Blade of the Grave,4,3.14,12.56
173,Stormfury Longsword,2,4.93,9.86
174,Primitive Blade,4,3.47,13.88
175,Woeful Adamantite Claymore,3,4.48,13.44
176,Relentless Iron Skewer,2,2.84,5.68
177,"Winterthorn, Defender of Shifting Worlds",2,2.08,4.16
178,"Oathbreaker, Last Hope of the Breaking Storm",12,4.23,50.76
179,"Wolf, Promise of the Moonwalker",6,4.48,26.88
180,Stormcaller,1,3.36,3.36
181,Reaper's Toll,5,1.66,8.30
182,Toothpick,3,4.03,12.09
183,Dragon's Greatsword,3,1.09,3.27

In [212]:
final_popular_table=final_popular_table.sort_values(['Purchase Count'], ascending=False)
final_popular_table

,,Purchase Count,Item Price,Total Purchase Value
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,4.23,50.76
145,Fiery Glass Crusader,9,4.58,41.22
82,Nirvana,9,4.90,44.10
108,"Extraction, Quickblade Of Trembling Hands",9,3.53,31.77
60,Wolf,8,3.54,28.32
34,Retribution Axe,8,2.22,17.76
75,Brutality Ivory Warmace,8,2.42,19.36
37,"Shadow Strike, Glory of Ending Hope",8,3.16,25.28
19,"Pursuit, Cudgel of Necromancy",8,1.02,8.16
72,Winter's Bite,8,3.77,30.16
59,"Lightning, Etcher of the King",8,4.23,33.84
92,Final Critic,8,4.88,39.04
103,Singed Scalpel,8,4.35,34.80
7,"Thorn, Satchel of Dark Souls",7,1.33,9.31
110,Suspension,7,1.44,10.08
71,Demise,7,1.61,11.27
164,Exiled Doomblade,7,1.63,11.41
85,Malificent Bag,7,1.75,12.25
117,"Heartstriker, Legacy of the Light",7,1.79,12.53
53,Vengeance Cleaver,7,2.05,14.35
78,"Glimmer, Ender of the Moon",7,4.40,30.80
141,Persuasion,7,3.19,22.33
159,"Oathbreaker, Spellblade of Trials",7,3.08,21.56
96,Blood-Forged Skeletal Spine,6,3.09,18.54
143,Frenzied Scimitar,6,1.56,9.36
160,Azurewrath,6,4.40,26.40
3,Phantomlight,6,2.49,14.94
2,Verdict,6,2.48,14.88
129,"Fate, Vengeance of Eternal Justice",6,1.54,9.24
25,Hero Cane,6,4.35,26.10
...,...,...,...,...
33,Curved Axe,2,1.16,2.32
26,Unholy Wand,2,1.12,2.24
28,"Flux, Destroyer of Due Diligence",2,1.06,2.12
125,Whistling Mithril Warblade,2,1.00,2.00
177,"Winterthorn, Defender of Shifting Worlds",2,2.08,4.16
127,"Heartseeker, Reaver of Souls",2,3.92,7.84
63,Stormfury Mace,2,4.99,9.98
43,Foul Edge,2,3.54,7.08
158,"Darkheart, Butcher of the Champion",2,2.45,4.90
48,"Rage, Legacy of the Lone Victor",2,2.48,4.96
14,Possessed Core,2,2.61,5.22
176,Relentless Iron Skewer,2,2.84,5.68
56,Foul Titanium Battle Axe,2,2.92,5.84
6,Rusty Skull,2,3.70,7.40
132,Persuasion,2,3.33,6.66
81,Dreamkiss,2,3.61,7.22
173,Stormfury Longsword,2,4.93,9.86
18,"Torchlight, Bond of Storms",2,4.65,9.30
104,Gladiator's Glaive,1,1.93,1.93
23,Crucifer,1,1.99,1.99
126,Exiled Mithril Longsword,1,2.00,2.00
118,"Ghost Reaver, Longsword of Magic",1,2.17,2.17
134,Undead Crusader,1,4.50,4.50
90,Betrayer,1,2.94,2.94
51,Endbringer,1,4.66,4.66
27,"Riddle, Tribute of Ended Dreams",1,3.30,3.30
180,Stormcaller,1,3.36,3.36
47,"Alpha, Reach of Ending Hope",1,3.58,3.58
91,Celeste,1,4.17,4.17
42,The Decapitator,1,1.75,1.75

In [213]:
final_popular_table.head()

,,Purchase Count,Item Price,Total Purchase Value
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,4.23,50.76
145,Fiery Glass Crusader,9,4.58,41.22
82,Nirvana,9,4.90,44.10
108,"Extraction, Quickblade Of Trembling Hands",9,3.53,31.77
60,Wolf,8,3.54,28.32

In [214]:
final_most_valuable_table=final_popular_table.sort_values(['Total Purchase Value'], ascending=False)
final_most_valuable_table

,,Purchase Count,Item Price,Total Purchase Value
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,4.23,50.76
82,Nirvana,9,4.90,44.10
145,Fiery Glass Crusader,9,4.58,41.22
92,Final Critic,8,4.88,39.04
103,Singed Scalpel,8,4.35,34.80
59,"Lightning, Etcher of the King",8,4.23,33.84
108,"Extraction, Quickblade Of Trembling Hands",9,3.53,31.77
78,"Glimmer, Ender of the Moon",7,4.40,30.80
72,Winter's Bite,8,3.77,30.16
60,Wolf,8,3.54,28.32
179,"Wolf, Promise of the Moonwalker",6,4.48,26.88
160,Azurewrath,6,4.40,26.40
25,Hero Cane,6,4.35,26.10
37,"Shadow Strike, Glory of Ending Hope",8,3.16,25.28
139,"Mercy, Katana of Dismay",5,4.94,24.70
128,"Blazeguard, Reach of Eternity",5,4.91,24.55
138,"Peacekeeper, Wit of Dark Magic",5,4.74,23.70
141,Persuasion,7,3.19,22.33
87,"Deluge, Edge of the West",5,4.43,22.15
159,"Oathbreaker, Spellblade of Trials",7,3.08,21.56
136,Ghastly Adamantite Protector,6,3.58,21.48
65,Conqueror Adamantite Mace,5,4.24,21.20
101,Final Critic,5,4.19,20.95
102,Avenger,6,3.44,20.64
133,Faith's Scimitar,5,4.09,20.45
39,"Betrayal, Whisper of Grieving Widows",5,3.94,19.70
111,Misery's End,4,4.89,19.56
165,Bone Crushing Silver Skewer,4,4.86,19.44
52,Hatred,4,4.84,19.36
75,Brutality Ivory Warmace,8,2.42,19.36
...,...,...,...,...
124,Venom Claymore,4,1.29,5.16
0,Splinter,4,1.28,5.12
155,War-Forged Gold Deflector,5,1.01,5.05
48,"Rage, Legacy of the Lone Victor",2,2.48,4.96
158,"Darkheart, Butcher of the Champion",2,2.45,4.90
51,Endbringer,1,4.66,4.66
134,Undead Crusader,1,4.50,4.50
30,Stormcaller,2,2.21,4.42
135,Warped Diamond Crusader,3,1.40,4.20
91,Celeste,1,4.17,4.17
177,"Winterthorn, Defender of Shifting Worlds",2,2.08,4.16
70,Hope's End,4,1.03,4.12
115,Spectral Diamond Doomblade,2,2.04,4.08
69,"Frenzy, Defender of the Harvest",2,1.98,3.96
47,"Alpha, Reach of Ending Hope",1,3.58,3.58
180,Stormcaller,1,3.36,3.36
27,"Riddle, Tribute of Ended Dreams",1,3.30,3.30
183,Dragon's Greatsword,3,1.09,3.27
31,Trickster,2,1.55,3.10
168,"Sun Strike, Jaws of Twisted Visions",2,1.48,2.96
90,Betrayer,1,2.94,2.94
33,Curved Axe,2,1.16,2.32
26,Unholy Wand,2,1.12,2.24
118,"Ghost Reaver, Longsword of Magic",1,2.17,2.17
28,"Flux, Destroyer of Due Diligence",2,1.06,2.12
125,Whistling Mithril Warblade,2,1.00,2.00
126,Exiled Mithril Longsword,1,2.00,2.00
23,Crucifer,1,1.99,1.99
104,Gladiator's Glaive,1,1.93,1.93
42,The Decapitator,1,1.75,1.75

In [215]:
final_most_valuable_table.head()

,,Purchase Count,Item Price,Total Purchase Value
Item ID,Item Name,,,
178,"Oathbreaker, Last Hope of the Breaking Storm",12,4.23,50.76
82,Nirvana,9,4.90,44.10
145,Fiery Glass Crusader,9,4.58,41.22
92,Final Critic,8,4.88,39.04
103,Singed Scalpel,8,4.35,34.80